# Generated by Django 4.2 on 2023-05-01 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Cep Telefonu'),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='office_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='İş Telefonu'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı'),
        ),
    ]
