# Generated by Django 4.2 on 2023-05-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_businessstaff_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='sharing',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='İlan Sayısı'),
        ),
    ]
