# Generated by Django 4.2 on 2023-05-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_businessstaff_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Açık Adres'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='sharing',
            field=models.CharField(blank=True, default=0, max_length=8, null=True, verbose_name='İlan Sayısı'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='social_media',
            field=models.TextField(blank=True, null=True, verbose_name='Sosyal Medya'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Site'),
        ),
    ]
