# Generated by Django 4.2 on 2023-05-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_businessstaff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kullanıcı Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Kullanıcı Dükkan Sahibi mi?'),
        ),
    ]
