# Generated by Django 4.2 on 2023-05-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_businessstaff_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessstaff',
            name='is_active',
        ),
    ]
