# Generated by Django 4.2 on 2023-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_businessstaff_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessstaff',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='businessstaff',
            name='website',
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='avatar',
            field=models.FileField(blank=True, default='user/user_image_default/avatar.png', upload_to='user/user_images/'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
    ]
