# Generated by Django 4.2 on 2023-05-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_businessstaff_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='avatar',
            field=models.FileField(blank=True, default='user/user_image_default/avatar.png', null=True, upload_to='user/user_images/'),
        ),
    ]
