# Generated by Django 4.2 on 2023-05-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_businessstaff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='avatar',
            field=models.FileField(blank=True, default='user/user_image_default/avatar.png', null=True, upload_to='uploads/'),
        ),
    ]
