# Generated by Django 4.2 on 2023-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_businessstaff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
