# Generated by Django 4.2 on 2023-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_businessstaff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='address',
            field=models.TextField(null=True, verbose_name='Açık Adres'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='avatar',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='biography',
            field=models.TextField(null=True, verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='mobile_phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='Cep Telefonu'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='office_phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='İş Telefonu'),
        ),
    ]
