# Generated by Django 4.2 on 2023-05-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_businessstaff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Kullanıcı Aktif mi?'),
        ),
    ]
