# Generated by Django 4.2 on 2023-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_businessstaff_office_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='social_media_facebook',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook Sosyal Medya'),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='social_media_instagram',
            field=models.TextField(blank=True, null=True, verbose_name='İnstagram Sosyal Medya'),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='social_media_tiktok',
            field=models.TextField(blank=True, null=True, verbose_name='Tiktok Sosyal Medya'),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='social_media_twitter',
            field=models.TextField(blank=True, null=True, verbose_name='Twitter Sosyal Medya'),
        ),
    ]
