# Generated by Django 4.2 on 2023-05-06 12:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='İlan Aktif mi?')),
                ('phone_brand', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefon Markası')),
                ('phone_model', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefon Modeli')),
                ('os', models.CharField(blank=True, default='Android', max_length=8, null=True, verbose_name='Telefon İşltem Sistemi')),
                ('ram_memory', models.CharField(blank=True, max_length=5, null=True, verbose_name='Telefon Ram Bellek')),
                ('memory_memory', models.CharField(blank=True, max_length=5, null=True, verbose_name='Telefon Hafıza Bellek')),
                ('situation', models.CharField(blank=True, default='İkinci El', max_length=10, null=True, verbose_name='Telefon Durumu')),
                ('garanti', models.CharField(blank=True, default='Garantisi Yok', max_length=21, null=True, verbose_name='Garanti')),
                ('swap', models.CharField(blank=True, max_length=6, null=True, verbose_name='Takas Durumu')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name=' İlçe')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhoneSales', to=settings.AUTH_USER_MODEL, verbose_name='İlan Sahibi')),
            ],
        ),
    ]
