# Generated by Django 4.2 on 2023-05-07 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0003_alter_phonesales_avatar_alter_phonesales_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='İlan Aktif mi?')),
                ('phone_brand', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefon Markası')),
                ('phone_model', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefon Modeli')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name=' İlçe')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='MobileRepair/', verbose_name='Tamir Resmi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MobileRepair', to=settings.AUTH_USER_MODEL, verbose_name='İlan Sahibi')),
            ],
        ),
    ]
