# Generated by Django 4.2 on 2023-05-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_mobilerepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilerepair',
            name='label',
            field=models.CharField(blank=True, default='Telefon-Tamir', max_length=50, null=True, verbose_name='Etiket(Telefon-Tamir)'),
        ),
        migrations.AddField(
            model_name='phonesales',
            name='label',
            field=models.CharField(blank=True, default='Telefon-Satış', max_length=50, null=True, verbose_name='Etiket(Telefon Satış)'),
        ),
    ]
