# Generated by Django 4.2 on 2023-05-07 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0005_mobilerepair_label_phonesales_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='İlan Aktif mi?')),
                ('label', models.CharField(blank=True, default='Telefon-Parçası', max_length=50, null=True, verbose_name='Etiket(Telefon-Parçası)')),
                ('part_name', models.CharField(blank=True, max_length=110, null=True, verbose_name='Telefon-Parçası')),
                ('situation', models.CharField(blank=True, default='İkinci El', max_length=10, null=True, verbose_name='Telefon Durumu')),
                ('garanti', models.CharField(blank=True, default='Garantisi Yok', max_length=21, null=True, verbose_name='Garanti')),
                ('swap', models.CharField(blank=True, max_length=6, null=True, verbose_name='Takas Durumu')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name=' İlçe')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='PhonePart/', verbose_name='Tamir Resmi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhonePart', to=settings.AUTH_USER_MODEL, verbose_name='İlan Sahibi')),
            ],
        ),
    ]
