# Generated by Django 4.2 on 2023-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_alter_phonepart_price_alter_phonesales_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesales',
            name='memory_memory',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Telefon Hafıza Bellek'),
        ),
        migrations.AlterField(
            model_name='phonesales',
            name='ram_memory',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Telefon Ram Bellek'),
        ),
    ]
