# Generated by Django 4.2 on 2023-05-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0010_alter_phonesales_avatar_alter_phonesales_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesales',
            name='comment',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
    ]
