# Generated by Django 4.1.7 on 2023-05-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0011_alter_phonesales_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilerepair',
            name='avatar',
            field=models.FileField(null=True, upload_to='MobileRepair/', verbose_name='Tamir Resmi'),
        ),
        migrations.AlterField(
            model_name='mobilerepair',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='mobilerepair',
            name='comment',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='mobilerepair',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name=' İlçe'),
        ),
        migrations.AlterField(
            model_name='mobilerepair',
            name='phone_brand',
            field=models.CharField(max_length=250, null=True, verbose_name='Telefon Markası'),
        ),
        migrations.AlterField(
            model_name='mobilerepair',
            name='phone_model',
            field=models.CharField(max_length=250, null=True, verbose_name='Telefon Modeli'),
        ),
    ]
