# Generated by Django 4.1.7 on 2023-05-09 22:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0012_alter_mobilerepair_avatar_alter_mobilerepair_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilerepair',
            name='label',
            field=models.CharField(default='Telefon-Tamir', max_length=50, null=True, verbose_name='Etiket(Telefon-Tamir)'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='aksesuar_name',
            field=models.CharField(max_length=110, null=True, verbose_name='Aksesuar Adı'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='avatar',
            field=models.FileField(null=True, upload_to='PhoneAksesuar/', verbose_name='İlan Resmi'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='comment',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name=' İlçe'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='label',
            field=models.CharField(default='Telefon-Aksesuar', max_length=50, null=True, verbose_name='Telefon-Aksesuarı'),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='phoneaksesuar',
            name='situation',
            field=models.CharField(default='İkinci El', max_length=10, null=True, verbose_name='Aksesuar Durumu'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='avatar',
            field=models.FileField(null=True, upload_to='PhonePart/', verbose_name='Tamir Resmi'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='comment',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name=' İlçe'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='garanti',
            field=models.CharField(default='Garantisi Yok', max_length=21, null=True, verbose_name='Garanti'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='label',
            field=models.CharField(default='Telefon-Parçası', max_length=50, null=True, verbose_name='Etiket(Telefon-Parçası)'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='part_name',
            field=models.CharField(max_length=110, null=True, verbose_name='Telefon-Parçası'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='situation',
            field=models.CharField(default='İkinci El', max_length=10, null=True, verbose_name='Telefon Durumu'),
        ),
        migrations.AlterField(
            model_name='phonepart',
            name='swap',
            field=models.CharField(max_length=6, null=True, verbose_name='Takas Durumu'),
        ),
    ]
