# Generated by Django 4.2 on 2023-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0013_alter_mobilerepair_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilerepair',
            name='jobfinish',
            field=models.BooleanField(default=False, verbose_name='Ürün Teslim Edildi Mi?'),
        ),
    ]
