# Generated by Django 4.2 on 2023-05-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0016_alter_phonesales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesales',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
