# Generated by Django 4.2 on 2023-05-11 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.BooleanField(default=False, verbose_name='İstek Onaylı Mı?')),
                ('jobfinish', models.BooleanField(default=False, verbose_name='Ürün Teslim Edildi Mi?')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(max_length=100, null=True, verbose_name=' İlçe')),
                ('phone_brand', models.CharField(max_length=250, null=True, verbose_name='Telefon Markası')),
                ('phone_model', models.CharField(max_length=250, null=True, verbose_name='Telefon Modeli')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('jobfinish_created_date', models.DateTimeField(verbose_name='Teslim Tarihi')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
