# Generated by Django 4.2 on 2023-05-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_phonerepairrequest_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonerepairrequest',
            name='jobfinish_created_date',
        ),
    ]
