# Generated by Django 4.2 on 2023-05-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0014_mobilerepair_jobfinish'),
        ('hospital', '0003_remove_phonerepairrequest_jobfinish_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonerepairrequest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='advert.mobilerepair', verbose_name='Hangi İlan'),
        ),
    ]
