# Generated by Django 4.2 on 2023-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_phonerepairrequest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonerepairrequest',
            name='product',
            field=models.IntegerField(null=True, verbose_name='Hangi İlan'),
        ),
    ]
