# Generated by Django 4.2 on 2023-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_phonerepairrequest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonerepairrequest',
            name='jobfinish_business',
            field=models.BooleanField(default=False, verbose_name='Ürün Teslim Edildi Mi? İşletme Sahibi Onay'),
        ),
        migrations.AlterField(
            model_name='phonerepairrequest',
            name='jobfinish',
            field=models.BooleanField(default=False, verbose_name='Ürün Teslim Edildi Mi? Telefon Sahibi Onay'),
        ),
    ]
